# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptive_C <- function(y, betas, u, c, G = 10) {
    .Call('_caviar_adaptive_C', PACKAGE = 'caviar', y, betas, u, c, G)
}

AS_C <- function(y, betas, u, c) {
    .Call('_caviar_AS_C', PACKAGE = 'caviar', y, betas, u, c)
}

ar_ES_C <- function(y, Q, gammas, x = as.numeric( c())) {
    .Call('_caviar_ar_ES_C', PACKAGE = 'caviar', y, Q, gammas, x)
}

mult_ES_C <- function(y, Q, gammas) {
    .Call('_caviar_mult_ES_C', PACKAGE = 'caviar', y, Q, gammas)
}

al_log_loss_function_C <- function(y, Q, ES, c) {
    .Call('_caviar_al_log_loss_function_C', PACKAGE = 'caviar', y, Q, ES, c)
}

SAV_C <- function(y, betas, u, c) {
    .Call('_caviar_SAV_C', PACKAGE = 'caviar', y, betas, u, c)
}

gjrGARCH_C <- function(y, betas, u, c) {
    .Call('_caviar_gjrGARCH_C', PACKAGE = 'caviar', y, betas, u, c)
}

indirectGARCH_C <- function(y, betas, u, c) {
    .Call('_caviar_indirectGARCH_C', PACKAGE = 'caviar', y, betas, u, c)
}

linearGARCH_C <- function(y, betas, u, c) {
    .Call('_caviar_linearGARCH_C', PACKAGE = 'caviar', y, betas, u, c)
}

linearTGARCH_C <- function(y, betas, u, c) {
    .Call('_caviar_linearTGARCH_C', PACKAGE = 'caviar', y, betas, u, c)
}

